baseURL = "http://blog.streacs.com/"
languageCode = "en-us"
title = "Just another weblog "
theme = "fishbone"

[params]
  author = "Oliver Wolf"
  email = "oliver.wolf@streacs.com"

[markup.goldmark.renderer]
  unsafe= true